### ISSUE TITLE
请教一下贷款银行怎么选择

### ISSUE THREAD

**Issue by nuistcz** [DongDavid/2020-House-purchase-record-in-Hangzhou#1]
老哥你好，我是20年11月摇中的，还没等到网签，但是首付已经交了，银行都说利率是5.15，想请问下从哪个银行能谈到5.05呢

**Comment by DongDavid** [comment]
我选择的是交通银行。
当时我记得交通和浙商银行的都是可以放到5.05的。
现在不晓得有没有变化

**Comment by gaohaizhen** [comment]
你好，摇号能取到房票的难度大不大

**Comment by DongDavid** [comment]
> 你好，摇号能取到房票的难度大不大

不好意思， 都没看到这个。 
这东西看脸了啊， 你要摇性价比很高的房子， 那肯定是很难的吧，
 除非你全款， 那么找人沟通一下， 我觉得还是有那么点操作可以让你摇中的。

普通的楼盘看脸了吧，摇中了万一摇的很靠后， 那还不如摇不中呢。
